### ISSUE TITLE
Connection error when using other models

### ISSUE THREAD

**Issue by InstaZDLL** [obiscr/ChatGPTGold#4]
[EN]
I have a problem when I want to use **another model**, I have this error, I changed the **server url endpoint** as indicated by OpenAI [here](https://platform.openai.com/docs/models/model-endpoint-compatibility).

In my example, I wanted to use **text-davinci-003** but it doesn't work for all the other models except **gpt4** (which I can't test), **gpt3-turbo** and **gpt3-turbo-0301**.

![Screenshot 2023-05-13 212044](https://github.com/obiscr/ChatGPTGold/assets/72951793/60ae2147-4b6d-4651-ac48-67a4d27c93e8)

Even if I **uncheck the box** I have the same problem (My settings) : **what am I doing wrong ?**

![Screenshot 2023-05-13 212111](https://github.com/obiscr/ChatGPTGold/assets/72951793/ce84ef4e-77cb-42f3-a054-2b5c471f680c)

[CN] third part translation tool - 第三部分翻译工具
我有这样的问题，当我想使用**的另一个模型时，我有这样的错误，我改变了OpenAI所指示的**服务器的URL端点[这里](https://platform.openai.com/docs/models/model-endpoint-compatibility).

在我的例子中，我想使用**text-davinci-003**，但除了**gpt4**（我无法测试）、**gpt3-turbo**和**gpt3-turbo-0301**，它对所有其他型号都不起作用。

即使我取消勾选，也有同样的问题（我的设置）：我做错了什么？

**Comment by obiscr** [comment]
Hi, @InstaZDLL 
```
The official Server URL is: https://api.openai.com/v1/chat/completions
And you fill in is:         https://api.openai.com/v1/completions
```
The `/chat` has been lost in your configuration.

For model:
If you select the gpt-4, It is only useful for accounts that have GPT-4 access. If your account does not yet have GPT-4 access, then you will not be able to use GPT-4.

You also mentioned the `text-davinci-003` model, which should be caused by the official API :https://api.openai.com/v1/chat/completions not being supported.

**Comment by InstaZDLL** [comment]
Ok so we can't use **text-davinci-003** with this plugin because even if I put **/chat** or **not** I get the same error even though it's well presented on the **OpenAI** website : 
![Screenshot 2023-05-15 073046](https://github.com/obiscr/ChatGPTGold/assets/72951793/6e5ecd45-27d7-413e-9b83-c1cb1540469d)

**Comment by obiscr** [comment]
Thank you for the information, I will test it further.

**Comment by obiscr** [comment]
After testing and consulting the official documentation, I have found that this is a bug. The error occurs because the data structure has changed. However, currently, apart from the `gpt-4` model, `gpt-3.5-turbo` should be the best model available. Previous models like `text-davinci-003` and `text-davinci-002` were not as useful as `gpt-3.5-turbo`. Therefore, there are no plans to support the older models unless it is absolutely necessary.
